Organization.create(name: 'Philippine Ruby Users Group')
Organization.create(name: 'Drupal Pilipinas')
Organization.create(name: 'PHP Users Group Philippines')
Organization.create(name: 'Python Philippines')
Organization.create(name: 'Philippine .NET Users Group')
Organization.create(name: 'International Game Developers Assocation - Manila')
Organization.create(name: 'Philippine Web Designers Organization')
Organization.create(name: 'Philippine Android Developers Community')
Organization.create(name: 'Google Developers Group - Philippines')
Organization.create(name: 'Mozilla Philippines Community')
Organization.create(name: 'NSCoder Philippines')
Organization.create(name: 'Laravel Philippines')
Organization.create(name: 'ManilaJS')
